{"uuid": "36519ee7-2560-4146-9839-5fe8154a28b5", "children": ["074d7d5d-a1a0-45d3-a483-07cee770f908"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "trace": "  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\_pytest\\python.py\", line 701, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\_pytest\\python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\xyrj\\python\\HeiMaXiangMuTest\\autoToutiaoTest\\script\\app\\test_query_artical.py\", line 9, in setup_class\n    self.driver = DriverUtils.get_app_driver()\n  File \"D:\\xyrj\\python\\HeiMaXiangMuTest\\autoToutiaoTest\\utils.py\", line 142, in get_app_driver\n    cls.__app_driver = appium.webdriver.Remote(\"http://127.0.0.1:5037/wd/hub\", cap)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 155, in __init__\n    proxy\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\urllib3\\request.py\", line 80, in request\n    method, url, fields=fields, headers=headers, **urlopen_kw\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\urllib3\\request.py\", line 171, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\urllib3\\poolmanager.py\", line 330, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\urllib3\\util\\retry.py\", line 400, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n    raise value.with_traceback(tb)\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n    chunked=chunked,\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"d:\\xyrj\\python\\python\\lib\\site-packages\\urllib3\\connectionpool.py\", line 416, in _make_request\n    httplib_response = conn.getresponse()\n  File \"d:\\xyrj\\python\\python\\lib\\http\\client.py\", line 1321, in getresponse\n    response.begin()\n  File \"d:\\xyrj\\python\\python\\lib\\http\\client.py\", line 296, in begin\n    version, status, reason = self._read_status()\n  File \"d:\\xyrj\\python\\python\\lib\\http\\client.py\", line 265, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\n"}, "start": 1591927555271, "stop": 1591927555284}], "start": 1591927555271, "stop": 1591927555959}